pipeline {
    agent any

    stages {
        // stage('git checkout') {
        //     steps {
        //         git branch: 'main', url: 'https://github.com/TaosifAhmed88/Jenkins.git'
        //     }
        // }
        stage('terraform init') {
            steps {
                dir('Day-2 Pipeline SCM_Var_Env_Github_Action') {
                sh 'terraform init'
            }
            }
        }
        stage('terraform plan') {
            steps {
                dir('Day-2 Pipeline SCM_Var_Env_Github_Action') {
                sh 'terraform plan'
            }
            }
        }
        stage('terraform apply') {
            steps {
                dir('Day-2 Pipeline SCM_Var_Env_Github_Action') {
                sh 'terraform ${action} -auto-approve'
            }
            }
        }
    }
}
